from __future__ import annotations

import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from lib_utils import DATA, load_json

CAND_PATH = DATA / "candidates" / "latest-candidates.extracted.json"
if not CAND_PATH.exists():
    CAND_PATH = DATA / "candidates" / "latest-candidates.json"


def run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    print("$", " ".join(cmd))
    return subprocess.run(cmd, check=check, text=True, capture_output=False)


def main() -> int:
    candidates = load_json(CAND_PATH, [])
    if not candidates:
        print("No new candidate entries. No PR needed.")
        return 0

    run(["git", "config", "user.name", "github-actions[bot]"])
    run(["git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com"])

    # Copy extracted file to dated canonical path if needed.
    sync_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    dated = DATA / "candidates" / f"{sync_date}-candidates.extracted.json"
    if CAND_PATH != dated:
        dated.write_text(CAND_PATH.read_text(encoding="utf-8"), encoding="utf-8")

    status = subprocess.run(["git", "status", "--porcelain"], text=True, capture_output=True, check=True).stdout.strip()
    if not status:
        print("No file changes. No PR needed.")
        return 0

    branch = f"auto/upstream-sync-{sync_date}"
    run(["git", "checkout", "-B", branch])
    run(["git", "add", "data/candidates", "data/upstream_snapshot.json", "data/parsed"], check=False)
    run(["git", "commit", "-m", f"Add upstream candidate entries for {sync_date}"], check=False)
    run(["git", "push", "--force", "--set-upstream", "origin", branch])

    names = [c.get("name", c.get("id", "Unnamed")) for c in candidates]
    body_lines = [
        "This draft PR was generated by the scheduled EO-FM upstream sync.",
        "",
        f"Detected candidate entries: {len(candidates)}",
        "",
    ]
    body_lines += [f"- {name}" for name in names[:40]]
    if len(names) > 40:
        body_lines.append(f"- … and {len(names) - 40} more")
    body_lines += [
        "",
        "Review checklist:",
        "- [ ] Same model appearing in multiple upstream lists has been merged, not duplicated",
        "- [ ] Paper URL points to the original source",
        "- [ ] Code / weights / project links are correct",
        "- [ ] Access status is correct",
        "- [ ] Modalities and architecture are supported by the source",
        "- [ ] Downstream tasks are specific and not hallucinated",
        "- [ ] Landscape fields are reasonable before promotion to `data/catalogue.json`",
        "",
        "Candidates are not shown in the verified public catalogue unless manually moved into `data/catalogue.json`.",
    ]
    body = "\n".join(body_lines)

    # Avoid creating duplicate open PRs for the same branch.
    existing = subprocess.run(["gh", "pr", "list", "--head", branch, "--json", "number", "--jq", ".[0].number"], text=True, capture_output=True)
    if existing.stdout.strip():
        print(f"PR already exists for {branch}: #{existing.stdout.strip()}")
        return 0

    run([
        "gh", "pr", "create",
        "--draft",
        "--title", f"Add candidate EO-FM entries from upstream sync: {sync_date}",
        "--body", body,
        "--base", "main",
        "--head", branch,
    ])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
